eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    host: 127.0.0.1
    port: 5672
  jpa:
   properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource:
      url: jdbc:postgresql://localhost:5432/dreamproject
      username: postgres
      password: postgres
      initialization-mode: always   
