eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    datasource:
      url: jdbc:postgresql://localhost:5432/dreamproject
      username: postgres
      password: postgres
      initialization-mode: always
